sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/shuup/build_resources"
    - "$HOME/.nvm"
env:
  - DEBUG=1
python:
  - "3.6"
install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install 4
  - pip install -U pip
  - pip install -r requirements-test.txt
script:
  - flake8
  - isort --check-only
  - py.test -ra -vvv --nomigrations --cov shuup_wishlist
after_success:
  - coveralls
  - codecov
